[0m15:34:00.894541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200BF206DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200BF206CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200BF277410>]}


============================== 15:34:00.910172 | 9d72feb1-4d01-4b4c-a6e2-e78232687823 ==============================
[0m15:34:00.910172 [info ] [MainThread]: Running with dbt=1.10.1
[0m15:34:00.910172 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt clean --profiles-dir dbt', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:34:00.910172 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:34:00.910172 [debug] [MainThread]: Command `dbt clean` failed at 15:34:00.910172 after 0.09 seconds
[0m15:34:00.910172 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200BF272E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200BF273150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200BF205D90>]}
[0m15:34:00.910172 [debug] [MainThread]: Flushing usage events
[0m15:34:01.406174 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:36:53.244039 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DEA4907910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DEA49072D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DEA49061D0>]}


============================== 15:36:53.244039 | 8e87e307-dc04-4a99-a4ec-d5f50a435f34 ==============================
[0m15:36:53.244039 [info ] [MainThread]: Running with dbt=1.10.1
[0m15:36:53.244039 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt clean', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:36:53.244039 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:36:53.244039 [debug] [MainThread]: Command `dbt clean` failed at 15:36:53.244039 after 0.09 seconds
[0m15:36:53.244039 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DEA4972E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DEA4973150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DE9E102D50>]}
[0m15:36:53.259664 [debug] [MainThread]: Flushing usage events
[0m15:36:53.754126 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:01:53.283515 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0717FED50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0717FBCD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0717FC590>]}


============================== 17:01:53.287961 | eb1bd739-6cf2-4c1d-985e-b95538c39f41 ==============================
[0m17:01:53.287961 [info ] [MainThread]: Running with dbt=1.10.1
[0m17:01:53.290324 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --select staging', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:01:53.291325 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:01:53.293502 [debug] [MainThread]: Command `dbt run` failed at 17:01:53.293502 after 0.10 seconds
[0m17:01:53.294504 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0717FE310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F06AF22C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F06AF22CD0>]}
[0m17:01:53.294504 [debug] [MainThread]: Flushing usage events
[0m17:01:53.809575 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:38:54.432260 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E90615FA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E90615CDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E90615C550>]}


============================== 17:38:54.432260 | 8326cc15-17f5-4cbf-a5b7-4423edf1b137 ==============================
[0m17:38:54.432260 [info ] [MainThread]: Running with dbt=1.10.1
[0m17:38:54.432260 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --select core_audit_flags', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:38:54.492702 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:38:54.494538 [debug] [MainThread]: Command `dbt run` failed at 17:38:54.494538 after 0.14 seconds
[0m17:38:54.495537 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9060E6190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E90615E850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9060F4850>]}
[0m17:38:54.495537 [debug] [MainThread]: Flushing usage events
[0m17:38:55.066430 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:39:00.663179 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000159154AB890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000159154AFA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000159154C0150>]}


============================== 17:39:00.670141 | 4bca66ba-7833-466d-959f-929e7ae57a1d ==============================
[0m17:39:00.670141 [info ] [MainThread]: Running with dbt=1.10.1
[0m17:39:00.671703 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --select core_audit_flags', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:39:00.673363 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:39:00.676218 [debug] [MainThread]: Command `dbt run` failed at 17:39:00.676218 after 0.14 seconds
[0m17:39:00.678218 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015915435F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000159154AB890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000159154ABE10>]}
[0m17:39:00.679667 [debug] [MainThread]: Flushing usage events
[0m17:39:01.162615 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:01:50.587985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002379938FC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002379938FE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002379938D810>]}


============================== 18:01:50.587985 | b5abecad-1877-42fc-a82a-8be4753af69c ==============================
[0m18:01:50.587985 [info ] [MainThread]: Running with dbt=1.10.1
[0m18:01:50.587985 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select mart_finanza_locale', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:01:50.587985 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:01:50.587985 [debug] [MainThread]: Command `dbt run` failed at 18:01:50.587985 after 0.09 seconds
[0m18:01:50.587985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023799315ED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023799327F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023799324590>]}
[0m18:01:50.587985 [debug] [MainThread]: Flushing usage events
[0m18:01:51.115395 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:01:17.007535 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000237763568D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023772F9F690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023776106290>]}


============================== 22:01:17.027989 | b36525ae-cc44-4bf8-8bd7-7ec7b72d7610 ==============================
[0m22:01:17.027989 [info ] [MainThread]: Running with dbt=1.9.3
[0m22:01:17.027989 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:01:17.407550 [info ] [MainThread]: dbt version: 1.9.3
[0m22:01:17.417570 [info ] [MainThread]: python version: 3.11.0
[0m22:01:17.417570 [info ] [MainThread]: python path: C:\Users\Andrea\AppData\Local\pypoetry\Cache\virtualenvs\mini-lakehouse-bmzhcIPO-py3.11\Scripts\python.exe
[0m22:01:17.417570 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m22:01:17.417570 [info ] [MainThread]: Using profiles dir at C:\Users\Andrea\.dbt
[0m22:01:17.417570 [info ] [MainThread]: Using profiles.yml file at C:\Users\Andrea\.dbt\profiles.yml
[0m22:01:17.417570 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
[0m22:01:17.425071 [info ] [MainThread]: Configuration:
[0m22:01:17.427069 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m22:01:17.428069 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m22:01:17.430068 [info ] [MainThread]: Required dependencies:
[0m22:01:17.431068 [debug] [MainThread]: Executing "git --help"
[0m22:01:17.612598 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m22:01:17.612598 [debug] [MainThread]: STDERR: "b''"
[0m22:01:17.617632 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m22:01:17.617632 [info ] [MainThread]: Connection test skipped since no profile was found
[0m22:01:17.617632 [info ] [MainThread]: [31m2 checks failed:[0m
[0m22:01:17.617632 [info ] [MainThread]: dbt looked for a profiles.yml file in C:\Users\Andrea\.dbt\profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m22:01:17.633857 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml> not found

[0m22:01:17.637856 [debug] [MainThread]: Command `dbt debug` failed at 22:01:17.637856 after 0.76 seconds
[0m22:01:17.639484 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000237763556D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002376FA92C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000237763128D0>]}
[0m22:01:17.640614 [debug] [MainThread]: Flushing usage events
[0m22:01:18.306649 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:05:48.013249 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A9BB4B31D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A9BE5BDE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A9BE796A10>]}


============================== 23:05:48.018224 | ba958048-ed43-4de6-8be1-4953f54fe015 ==============================
[0m23:05:48.018224 [info ] [MainThread]: Running with dbt=1.9.3
[0m23:05:48.019214 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run --select raw_bilanci', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:05:48.020215 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:05:48.022215 [debug] [MainThread]: Command `dbt run` failed at 23:05:48.022215 after 0.09 seconds
[0m23:05:48.023215 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A9BE7FA510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A9BE7FB350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A9BE794610>]}
[0m23:05:48.023215 [debug] [MainThread]: Flushing usage events
[0m23:05:48.557398 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:58:02.872075 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81F3F6B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81F0C3F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81F454DD0>]}


============================== 14:58:03.012705 | 89585abf-3e80-4cb0-98aa-1a7a1abe038a ==============================
[0m14:58:03.012705 [info ] [MainThread]: Running with dbt=1.9.3
[0m14:58:03.012705 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt parse', 'send_anonymous_usage_stats': 'True'}
[0m14:58:03.012705 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:58:03.036351 [debug] [MainThread]: Command `dbt parse` failed at 14:58:03.035348 after 0.24 seconds
[0m14:58:03.037906 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81F427890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81DEB5B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81F3F5BD0>]}
[0m14:58:03.057719 [debug] [MainThread]: Flushing usage events
[0m14:58:03.774463 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:13:15.189979 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EDC5555B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EDC55C1990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EDC55C0E50>]}


============================== 12:13:15.236864 | b023b872-69a3-46ab-bbab-9137be7b0413 ==============================
[0m12:13:15.236864 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:13:15.236864 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt clean', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:13:15.236864 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:13:15.252484 [debug] [MainThread]: Command `dbt clean` failed at 12:13:15.252484 after 0.13 seconds
[0m12:13:15.252484 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EDBED53050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EDC55C2110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EDC55C1810>]}
[0m12:13:15.252484 [debug] [MainThread]: Flushing usage events
[0m12:13:15.889108 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:33:02.874520 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000261E3EDBE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000261E3EE4BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000261E3BF00D0>]}


============================== 13:33:02.905770 | e84f8cef-1b77-45f6-a42c-2b787714eeca ==============================
[0m13:33:02.905770 [info ] [MainThread]: Running with dbt=1.9.3
[0m13:33:02.905770 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m13:33:02.905770 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:33:02.905770 [debug] [MainThread]: Command `dbt deps` failed at 13:33:02.905770 after 0.12 seconds
[0m13:33:02.905770 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000261E3BF0150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000261DD703C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000261DD703B90>]}
[0m13:33:02.905770 [debug] [MainThread]: Flushing usage events
[0m13:33:03.445242 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:09:12.880806 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C7685D18D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C7685669D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C7685D1A10>]}


============================== 15:09:12.880806 | 2625178d-15d6-4730-bffa-a982abeffd62 ==============================
[0m15:09:12.880806 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:09:12.880806 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed --full-refresh', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:09:12.880806 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:09:12.880806 [debug] [MainThread]: Command `dbt seed` failed at 15:09:12.880806 after 0.09 seconds
[0m15:09:12.896429 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C7685C8C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C7685CB150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C7685CAE50>]}
[0m15:09:12.896429 [debug] [MainThread]: Flushing usage events
[0m15:09:13.446413 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:39:57.157987 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C99DE5BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C99C0F190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C99DE7950>]}


============================== 15:39:57.173615 | f6fe72fc-ea96-4d0c-be0f-163bb4973552 ==============================
[0m15:39:57.173615 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:39:57.173615 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed --select bilanci_comunali_sample_temp', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:39:57.173615 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:39:57.173615 [debug] [MainThread]: Command `dbt seed` failed at 15:39:57.173615 after 0.14 seconds
[0m15:39:57.173615 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C99D08310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C99E4B150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C99E2D890>]}
[0m15:39:57.173615 [debug] [MainThread]: Flushing usage events
[0m15:39:57.737533 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:42:10.057861 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194A5961AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194A595BA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194A595B7D0>]}


============================== 15:42:10.073497 | a92f5425-fab7-4ff1-b6ac-0c3f875c4965 ==============================
[0m15:42:10.073497 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:42:10.073497 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt seed --full-refresh', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:42:10.073497 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:42:10.073497 [debug] [MainThread]: Command `dbt seed` failed at 15:42:10.073497 after 0.09 seconds
[0m15:42:10.073497 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194A43A5B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194A58F58D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194A58F7ED0>]}
[0m15:42:10.073497 [debug] [MainThread]: Flushing usage events
[0m15:42:10.600900 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:55:00.181354 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B3219CB890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B3219E58D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B3219E5D50>]}


============================== 15:55:00.181354 | 1ea983b8-f2a9-4efd-a020-47714460b008 ==============================
[0m15:55:00.181354 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:55:00.181354 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:55:00.181354 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:55:00.181354 [debug] [MainThread]: Command `dbt deps` failed at 15:55:00.181354 after 0.10 seconds
[0m15:55:00.181354 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B3219FDB10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B3219E5E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B31B113510>]}
[0m15:55:00.181354 [debug] [MainThread]: Flushing usage events
[0m15:55:00.731062 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:54:58.337732 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A09D15910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A09D17090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A09B3F4D0>]}


============================== 17:54:58.337732 | 60d4b703-903c-4e27-9099-185af245c2f8 ==============================
[0m17:54:58.337732 [info ] [MainThread]: Running with dbt=1.9.3
[0m17:54:58.337732 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Andrea\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt deps', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:54:58.337732 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Andrea\Documents\Mini Lakehouse Didattico\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:54:58.348509 [debug] [MainThread]: Command `dbt deps` failed at 17:54:58.348509 after 0.10 seconds
[0m17:54:58.349510 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A09D75810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A09D75E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A09D76E10>]}
[0m17:54:58.350510 [debug] [MainThread]: Flushing usage events
[0m17:54:58.856214 [debug] [MainThread]: An error was encountered while trying to flush usage events
